export const MAIN_PAGE = '/'
export const ADMIN_PAGE = '/admin'
export const PROFILE_PAGE = '/profile'
export const DEVICE_PAGE = '/device'
export const LOGIN_PAGE = '/login'
export const ERROR_PAGE = '/error'